### ISSUE TITLE
Error when start program

### ISSUE THREAD

**Issue by shankar667** [red5pro/red5pro-html5-hls#17]
Hi,
I am getting the error mentioned below, please suggest me anything missing?

Also please see the log file:
[npm-debug.zip](https://github.com/red5pro/red5pro-html5-hls/files/500642/npm-debug.zip)
 
`E:\wamp\www\red5pro-html5-hls>npm run start`

`> red5pro-html5-hls@1.0.0 start E:\wamp\www\red5pro-html5-hls`
`> npm run publish && PORT=3000 node index.js`

`> red5pro-html5-hls@1.0.0 publish E:\wamp\www\red5pro-html5-hls`
`> npm run lint && browserify -d -e js/main.js -o bundled/bundle.js -t [ babelify --presets [ es2015 ] ]`

`> red5pro-html5-hls@1.0.0 lint E:\wamp\www\red5pro-html5-hls`
`> standard js/**/*.js --verbose`

`standard: Use JavaScript Standard Style (https://github.com/feross/standard)`
  `E:\wamp\www\red5pro-html5-hls\js\demo-video-handler.js:178:1: Trailing spaces not allowed. (no-trailing-spaces)`
  `E:\wamp\www\red5pro-html5-hls\js\demo-video-handler.js:180:21: "XMLHttpRequest" is not defined. (no-undef)`

`npm ERR! Windows_NT 6.3.9600`
`npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"`
`npm ERR! node v0.12.7`
`npm ERR! npm  v2.11.3`
`npm ERR! code ELIFECYCLE`
`npm ERR! red5pro-html5-hls@1.0.0 lint: standard js/**/*.js --verbose`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the red5pro-html5-hls@1.0.0 lint script 'standard js/**/*.js --verbose'.`
`npm ERR! This is most likely a problem with the red5pro-html5-hls package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     standard js/**/*.js --verbose`
`npm ERR! You can get their info via:`
`npm ERR!     npm owner ls red5pro-html5-hls`
`npm ERR! There is likely additional logging output above.`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     E:\wamp\www\red5pro-html5-hls\npm-debug.log`

**Comment by HoldenMills** [comment]
Hi Shankar.  I have put your ticket into the queue on our support system and I shall respond to you as soon as I can.  Please be on the lookout for an e-mail from me.  For all future requests please submit them through this link: [https://red5pro.zendesk.com/hc/en-us/requests/new](https://red5pro.zendesk.com/hc/en-us/requests/new) Thanks and I will be in touch soon.

**Comment by sqow** [comment]
Hey Shankar, these issues have been resolved in the `develop` branch. Thank you for letting us know about them.
